global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Configuration;
global using System.Data;
global using System.Data.SQLite;
global using System.Drawing;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.ServiceProcess;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using Syncfusion.UI.Xaml.Grid;
global using CounterPOS.DBHelper;
global using CounterPOS.Common;
global using CounterPOS.Model;
global using CounterPOS.Properties;
global using CounterPOS.ViewModel;
global using CounterPOS.Views;
global using CounterPOS.Views.Category;
global using Dapper;
global using DevExpress.Mvvm;
global using HandyControl.Themes;
global using Microsoft.Win32;
global using Newtonsoft.Json;
global using Wpf.Ui.Appearance;
global using Wpf.Ui.Controls;
global using Brushes = System.Windows.Media.Brushes;
global using Window = System.Windows.Window;
global using System.Net.Http.Headers;
global using System.ComponentModel;
global using Microsoft.Extensions.DependencyInjection;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Diagnostics;
global using System.Windows;
global using Microsoft.Extensions.Hosting;
global using Forms = System.Windows.Forms;


