//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounterPOS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DefaultDiscountValue {
            get {
                return ((decimal)(this["DefaultDiscountValue"]));
            }
            set {
                this["DefaultDiscountValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInvoiceOnCreating {
            get {
                return ((bool)(this["ShowInvoiceOnCreating"]));
            }
            set {
                this["ShowInvoiceOnCreating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateUIMenuAtStartup {
            get {
                return ((bool)(this["CreateUIMenuAtStartup"]));
            }
            set {
                this["CreateUIMenuAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDefaultFBRInvoice {
            get {
                return ((bool)(this["IsDefaultFBRInvoice"]));
            }
            set {
                this["IsDefaultFBRInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DiscountAndTaxOnTotal {
            get {
                return ((bool)(this["DiscountAndTaxOnTotal"]));
            }
            set {
                this["DiscountAndTaxOnTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string LastUsedUsername {
            get {
                return ((string)(this["LastUsedUsername"]));
            }
            set {
                this["LastUsedUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double UIMenuButtonWidth {
            get {
                return ((double)(this["UIMenuButtonWidth"]));
            }
            set {
                this["UIMenuButtonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double UIMenuButtonHeight {
            get {
                return ((double)(this["UIMenuButtonHeight"]));
            }
            set {
                this["UIMenuButtonHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double UIMenuItemNameFontSize {
            get {
                return ((double)(this["UIMenuItemNameFontSize"]));
            }
            set {
                this["UIMenuItemNameFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double UIMenuItemProductImageWidth {
            get {
                return ((double)(this["UIMenuItemProductImageWidth"]));
            }
            set {
                this["UIMenuItemProductImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double UIMenuItemProductImageHeight {
            get {
                return ((double)(this["UIMenuItemProductImageHeight"]));
            }
            set {
                this["UIMenuItemProductImageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PictureWatermark {
            get {
                return ((bool)(this["PictureWatermark"]));
            }
            set {
                this["PictureWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextWatermark {
            get {
                return ((bool)(this["TextWatermark"]));
            }
            set {
                this["TextWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paid")]
        public string InvoiceWatermarkText {
            get {
                return ((string)(this["InvoiceWatermarkText"]));
            }
            set {
                this["InvoiceWatermarkText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 48pt")]
        public global::System.Drawing.Font InvoiceWatermarkFont {
            get {
                return ((global::System.Drawing.Font)(this["InvoiceWatermarkFont"]));
            }
            set {
                this["InvoiceWatermarkFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190")]
        public int InvoiceWatermarkTextTransparency {
            get {
                return ((int)(this["InvoiceWatermarkTextTransparency"]));
            }
            set {
                this["InvoiceWatermarkTextTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190")]
        public int InvoiceWatermarkImageTransparency {
            get {
                return ((int)(this["InvoiceWatermarkImageTransparency"]));
            }
            set {
                this["InvoiceWatermarkImageTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DefaultGSTValue {
            get {
                return ((decimal)(this["DefaultGSTValue"]));
            }
            set {
                this["DefaultGSTValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscountAndTaxPerItem {
            get {
                return ((bool)(this["DiscountAndTaxPerItem"]));
            }
            set {
                this["DiscountAndTaxPerItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cash")]
        public string DefaultPaymentType {
            get {
                return ((string)(this["DefaultPaymentType"]));
            }
            set {
                this["DefaultPaymentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public string ChangeToThemeName {
            get {
                return ((string)(this["ChangeToThemeName"]));
            }
            set {
                this["ChangeToThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string HandyTheme {
            get {
                return ((string)(this["HandyTheme"]));
            }
            set {
                this["HandyTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string WPFUITheme {
            get {
                return ((string)(this["WPFUITheme"]));
            }
            set {
                this["WPFUITheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#03A9F4")]
        public string AccentBrush {
            get {
                return ((string)(this["AccentBrush"]));
            }
            set {
                this["AccentBrush"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HeaderAutoFill {
            get {
                return ((bool)(this["HeaderAutoFill"]));
            }
            set {
                this["HeaderAutoFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public string HeaderLocation {
            get {
                return ((string)(this["HeaderLocation"]));
            }
            set {
                this["HeaderLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public string HeaderOrientation {
            get {
                return ((string)(this["HeaderOrientation"]));
            }
            set {
                this["HeaderOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double RowHeight {
            get {
                return ((double)(this["RowHeight"]));
            }
            set {
                this["RowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public double RowFontSize {
            get {
                return ((double)(this["RowFontSize"]));
            }
            set {
                this["RowFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCurrentSale {
            get {
                return ((bool)(this["ShowCurrentSale"]));
            }
            set {
                this["ShowCurrentSale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public short PrintCopies {
            get {
                return ((short)(this["PrintCopies"]));
            }
            set {
                this["PrintCopies"] = value;
            }
        }
    }
}
